### ISSUE TITLE
Error reading inputs SSH privates.

### ISSUE THREAD

**Issue by elysitcs** [easingthemes/ssh-deploy#120]
TypeError: Cannot read properties of undefined (reading 'split')
    at /home/runner/work/_actions/easingthemes/ssh-deploy/main/dist/index.js:2:4556
    at Array.forEach (<anonymous>)
    at Object.229 (/home/runner/work/_actions/easingthemes/ssh-deploy/main/dist/index.js:2:43[19](https://github.com/elysitcs/MediaWatch-Web-App/actions/runs/4234513882/jobs/7356907110#step:7:20))
    at __nccwpck_require__ (/home/runner/work/_actions/easingthemes/ssh-deploy/main/dist/index.js:2:8839)
    at Object.976 (/home/runner/work/_actions/easingthemes/ssh-deploy/main/dist/index.js:2:4805)
    at __nccwpck_require__ (/home/runner/work/_actions/easingthemes/ssh-deploy/main/dist/index.js:2:8839)
    at /home/runner/work/_actions/easingthemes/ssh-deploy/main/dist/index.js:2:9105
    at /home/runner/work/_actions/easingthemes/ssh-deploy/main/dist/index.js:2:9826
    at Object.<anonymous> (/home/runner/work/_actions/easingthemes/ssh-deploy/main/dist/index.js:2:9847)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)

**Comment by easingthemes** [comment]
Bug should be fixed, check with @ main or v4.1.5
https://github.com/easingthemes/ssh-deploy/issues/118

**Comment by williamspencer** [comment]
> Bug should be fixed, check with @ main or v4.1.5 #118

unfortunately still seeing this error, trying both `@main` and `@v4.1.5`

> TypeError: Cannot read properties of undefined (reading 'split')
    at /home/runner/work/_actions/easingthemes/ssh-deploy/v4.1.5/dist/index.js:2:4556
    at Array.forEach (<anonymous>)
    at Object.229 (/home/runner/work/_actions/easingthemes/ssh-deploy/v4.1.5/dist/index.js:2:43[19](https://github.com/TRAILS-to-wellness/trails-iwd/actions/runs/4234737084/jobs/7357449177#step:3:20))
    at __nccwpck_require__ (/home/runner/work/_actions/easingthemes/ssh-deploy/v4.1.5/dist/index.js:2:8874)
    at Object.976 (/home/runner/work/_actions/easingthemes/ssh-deploy/v4.1.5/dist/index.js:2:4805)
    at __nccwpck_require__ (/home/runner/work/_actions/easingthemes/ssh-deploy/v4.1.5/dist/index.js:2:8874)
    at /home/runner/work/_actions/easingthemes/ssh-deploy/v4.1.5/dist/index.js:2:9140
    at /home/runner/work/_actions/easingthemes/ssh-deploy/v4.1.5/dist/index.js:2:9861
    at Object.<anonymous> (/home/runner/work/_actions/easingthemes/ssh-deploy/v4.1.5/dist/index.js:2:9882)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)

**Comment by elysitcs** [comment]
It's still raising the same error.

**Comment by easingthemes** [comment]
New update released, main branch or v.4.1.6.

**Comment by williamspencer** [comment]
> New update released, main branch or v.4.1.6.

confirmed working on my end pointing to `@main` - thank you!

**Comment by easingthemes** [comment]
Great, thanks.

**Comment by GiantBabyCorn** [comment]
Same issue here,
Files' transferring is actually failed, while the workflow shows pass ( with an undetected error message: `Cannot read properties of undefined (reading 'substring')` ).

version: v4.1.6

```
[FILE] writing ***/local_ssh_script-before.sh file ... 25
Cannot read properties of undefined (reading 'substring')
```

![image](https://user-images.githubusercontent.com/82532128/220433630-40576a85-96c6-4cbf-9c84-53ec3edad168.png)
